### ISSUE TITLE
Add abilities

### ISSUE THREAD

**Issue by aj-r** [red3141/UrfChallenge2015#16]
e.g. zhonya's, banshee's, youmuu's

**Comment by aj-r** [comment]
Flash - moves in the current direction of motion. Flash a different distance based on focused / not focused?

**Comment by aj-r** [comment]
Maybe have a large set of abilities and you can choose 2-3 of them.

**Comment by red3141** [comment]
Randuin's: slows particles around you

**Comment by red3141** [comment]
Zhonya's and Flash are done.

**Comment by aj-r** [comment]
Randuin's done
