### ISSUE TITLE
Particles to fix

### ISSUE THREAD

**Issue by aj-r** [red3141/UrfChallenge2015#19]
Morde - bigger
Kennen - spinnable shuriken

**Comment by aj-r** [comment]
Nasus - bigger
Nautilus - longer

**Comment by red3141** [comment]
Morde done.
Nautilus done.

Still outstanding:
Kennen
Nasus
Teemo

**Comment by red3141** [comment]
Kennen done.

Still outstanding:
Nasus
Teemo

**Comment by aj-r** [comment]
Renekton - bigger
Riven - bigger

**Comment by red3141** [comment]
Renekton and Riven done.

Still outstanding:
Nasus
Teemo

**Comment by aj-r** [comment]
Trundle - bigger
Xin Zhao - bigger

**Comment by red3141** [comment]
Susan done.

Still outstanding:
Teemo
Trundle
Xin Zhao

**Comment by red3141** [comment]
Trundle done.

TODO:
Teemo
Xin Zhao
Vi
Cho'Gath

**Comment by red3141** [comment]
Cho'Gath done.

TODO:
Teemo
Xin Zhao
Vi
Quinn
Nocturne

**Comment by aj-r** [comment]
Nocturne darkness particle size: 1100 x 1400

**Comment by red3141** [comment]
Nocturne done.
TODO:
Vi
Xin Zhao
Quinn
Teemo

**Comment by red3141** [comment]
Vi, Xin, and Quinn done.

TODO:
Teemo
Olaf axe should be bigger

**Comment by red3141** [comment]
Olaf done.
TODO:
Teemo
J4

**Comment by red3141** [comment]
J4 done
TODO:
Teemo

**Comment by red3141** [comment]
Teemo done.
